name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check formatting
        uses: JosephNaberhaus/actions/go-check-formatting@v1.2.0
