name: Scraper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-scaper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run Scraper
        # Only run for an hour at a time. Otherwise, GitHub will kill the job.
        run: go run . -duration 3600
      - name: Push changes
        uses: JosephNaberhaus/actions/commit-and-push@v1.3.0
        with:
          message: Update dataset
